title: "The Costumemaster"
author: "Marquis Kurt"
author_url: "https://marquiskurt.net"
github_url: "https://github.com/alicerunsonfedora/CS400"
theme: jony

min_acl: internal
build_tool_arguments: ["-workspace", "Conscious.xcodeproj/project.xcworkspace", "-scheme" ,"Game", "-destination", "arch=arm64"]
documentation: "./Guides/*.md"

exclude: "./Conscious/Classes/App/*,./Conscious/Views/*,./Conscious/Assets/TealConverse.mlmodel/*"

custom_categories:
  - name: Information Center
    children:
    - Project Proposal
    - Privacy Policy
    
  - name: Game Data
    children:
    - CommandLineArguments
    - GameStore
    - Preferences

  - name: Game Levels
    children:
    - Creating a Level
    - GameScene
    - LevelDataConfiguration
    
  - name: Interface Scenes
    children:
    - AboutScene
    - EndGameScene
    - IntroScene
    - MainMenuScene
    - PauseScene
    - SplashScene
    
  - name: Inputs
    children:
    - GameSignalSender
    - GameSignalKind
    - GameSignalMethod
    - GameAchievementTrigger
    - GameAlarmClock
    - GameComputer
    - GameLever
    - GamePressurePlate
    - GameIrisScanner
    
  - name: Outputs
    children:
    - GameSignalReceivable
    - SwitchRequisite
    - DoorReceiver
    
  - name: Interactables
    children:
    - GameHeavyObject
    - Player
    
  - name: Artificial Intelligence Agents
    children:
    - Working With Agents
    - AIGameStrategy
    - AITreeStrategy
    
  - name: AI - Random Move Strategies
    children:
    - AIRandomMoveStrategist
    - AIRandomWeightedStrategist
    - AIReflexStrategist
    
  - name: AI - Decision Tree Strategies
    children:
    - AIPredeterminedTreeStrategist
    - AITealConverseStrategist
    
  - name: AI - Components
    children:
    - AIGameScene
    - AIAbstractGamePlayer
    - AIAbstractGameState
    - AIGameStrategist
    - AIAbstractGameSignalSender
    - AIAbstractGameSignalReceivable
    - AIGameDecision
    - AIGamePlayerAction
    
  - name: Challenges
    children:
    - ChallengeGameScene
    - CostumemasteryInheritable
    - CycleChallenge
    - DivergentChallenge
    - ExposureChallenge
    - RushedChallenge
    - SeededChallenge
    - VisibilityChallenge

  - name: Game Center
    children:
    - Game Center
    - GameAchievement
    - GameLeaderboard
    - GKAchievement
    - GKLeaderboard
